name: Build and unit test
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-images:
    name: Build Images
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:

          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          push: false
          load: true # Export to Docker Engine rather than pushing to a registry
          tags: ${{ github.run_id }}
          target: test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

          # for simple tests (npm test, etc.) just run a local image in docker
      - name: Unit Testing in Docker
        run: docker run --rm ${{ github.run_id }} echo "./mvnw test"

      - name: Docker Build and Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64,linux/arm/v7